[buildPlans.IosevkaDWB]
family = "Iosevka DWB"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.IosevkaDWB.variants]
  inherits = "ss08"

[buildPlans.IosevkaDWB.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaDWB.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaDWB.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaDWB.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaDWB.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaDWB.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
